name: Publish and commit bottles on schedule

on:
  schedule:
    # Once every hour
    - cron: '*/60 * * * *'

jobs:
  autopublish:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: ubuntu-latest
    env:
      HOMEBREW_COLOR: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
    steps:
      - name: Update Homebrew
        run: brew update-reset $(brew --repo)
      - name: Run automerge
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
        run: brew pr-automerge --verbose --publish
