name: Cancel previous runs

on: pull_request_target

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel
        uses: Homebrew/actions/cancel-previous-runs@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
